packages:
  - apps/*
  - packages/*
catalog:
  react-router: ^7.12.0
  "@react-router/dev": ^7.12.0
  "@react-router/node": ^7.12.0
  "@react-router/serve": ^7.12.0
  "@react-router/express": ^7.12.0
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@types/node": ^25.0.3
  isbot: ^5.1.32
  prettier: ^3.7.4
  react: ^19.2.3
  react-dom: ^19.2.3
  typescript: ^5.9.3
  vite: ^7.3.0
  vite-tsconfig-paths: ^6.0.2
  prisma: ^7.1.0
  "@prisma/client": ^7.1.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  tailwind-merge: ^3.4.0
  radix-ui: ^1.4.3
  zod: ^3.24.1
  date-fns: ^4.1.0
  lucide-react: ^0.561.0
  react-select: ^5.10.2
  sonner: ^2.0.7
  sharp: ^0.34.5
  bcrypt: ^6.0.0
  "@types/bcrypt": "^5.0.2"
  "@supabase/supabase-js": "^2.99.2"
  "@uppy/core": ^5.2.0
  "@uppy/dashboard": ^5.1.0
  "@uppy/react": ^5.1.1
  "@uppy/xhr-upload": ^5.1.1
  tailwindcss: ^4.1.18
  "@tailwindcss/vite": ^4.1.18
  "@tailwindcss/typography": ^0.5.19
  "@tiptap/core": ^3.15.3
  "@tiptap/extension-color": ^3.15.3
  "@tiptap/extension-emoji": ^3.15.3
  "@tiptap/extension-font-family": ^3.15.3
  "@tiptap/extension-highlight": ^3.15.3
  "@tiptap/extension-horizontal-rule": ^3.15.3
  "@tiptap/extension-image": ^3.15.3
  "@tiptap/extension-link": ^3.15.3
  "@tiptap/extension-list": ^3.15.3
  "@tiptap/extension-placeholder": ^3.15.3
  "@tiptap/extension-subscript": ^3.15.3
  "@tiptap/extension-superscript": ^3.15.3
  "@tiptap/extension-table": ^3.15.3
  "@tiptap/extension-table-cell": ^3.15.3
  "@tiptap/extension-table-header": ^3.15.3
  "@tiptap/extension-table-row": ^3.15.3
  "@tiptap/extension-text-align": ^3.15.3
  "@tiptap/extension-text-style": ^3.15.3
  "@tiptap/extension-typography": ^3.15.3
  "@tiptap/extension-underline": ^3.15.3
  "@tiptap/extension-youtube": ^3.15.3
  "@tiptap/extensions": ^3.15.3
  "@tiptap/pm": ^3.15.3
  "@tiptap/react": ^3.15.3
  "@tiptap/starter-kit": ^3.15.3
overrides:
  react-router: "catalog:"
  "@react-router/dev": "catalog:"
  "@react-router/node": "catalog:"
  "@react-router/serve": "catalog:"
  "@react-router/express": "catalog:"
  hono: ">=4.10.3"
  valibot: ">=1.2.0"
  "@types/react": "catalog:"
  "@types/react-dom": "catalog:"
  "@types/node": "catalog:"
  isbot: "catalog:"
  prettier: "catalog:"
  react: "catalog:"
  react-dom: "catalog:"
  typescript: "catalog:"
  vite: "catalog:"
  vite-tsconfig-paths: "catalog:"
  prisma: "catalog:"
  "@prisma/client": "catalog:"
  lucide-react: "catalog:"
  react-select: "catalog:"
  zod: "catalog:"
  sharp: "catalog:"
  "@tiptap/core": "catalog:"
  "@tiptap/extension-color": "catalog:"
  "@tiptap/extension-emoji": "catalog:"
  "@tiptap/extension-font-family": "catalog:"
  "@tiptap/extension-highlight": "catalog:"
  "@tiptap/extension-horizontal-rule": "catalog:"
  "@tiptap/extension-image": "catalog:"
  "@tiptap/extension-link": "catalog:"
  "@tiptap/extension-list": "catalog:"
  "@tiptap/extension-placeholder": "catalog:"
  "@tiptap/extension-subscript": "catalog:"
  "@tiptap/extension-superscript": "catalog:"
  "@tiptap/extension-table": "catalog:"
  "@tiptap/extension-table-cell": "catalog:"
  "@tiptap/extension-table-header": "catalog:"
  "@tiptap/extension-table-row": "catalog:"
  "@tiptap/extension-text-align": "catalog:"
  "@tiptap/extension-text-style": "catalog:"
  "@tiptap/extension-typography": "catalog:"
  "@tiptap/extension-underline": "catalog:"
  "@tiptap/extension-youtube": "catalog:"
  "@tiptap/extensions": "catalog:"
  "@tiptap/pm": "catalog:"
  "@tiptap/react": "catalog:"
  "@tiptap/starter-kit": "catalog:"
