import { prisma } from "@repo/database";
import * as fs from "fs";
import * as path from "path";

async function generatePermissionsFile() {
  console.log("📝 Fetching admin_permissions from database...");
  const permissionsData = await prisma.admin_permissions.findMany({
    select: {
      id: true,
      name: true,
      display_name: true,
      description: true,
      category: true,
      is_dangerous: true,
    },
    orderBy: {
      name: "asc",
    },
  });

  if (!permissionsData || permissionsData.length === 0) {
    console.warn("⚠️  No permissions found in admin_permissions table.");
    return;
  }

  const admin_permissions = permissionsData;
  const permissions: Record<string, any> = {};
  const permissionIdToNameMap = new Map<string, string>();

  permissionsData.forEach((p) => {
    const [category, name] = p.name.split(".");
    if (!permissions[category]) {
      permissions[category] = {};
    }
    permissions[category][name] = p.name;
    permissionIdToNameMap.set(p.id, p.name);
  });

  // Fetch admin_roles
  console.log("👥 Fetching admin_roles from database...");
  const rolesData = await prisma.admin_roles.findMany({
    select: {
      id: true,
      name: true,
      display_name: true,
      description: true,
      is_active: true,
      level: true,
      created_at: true,
      updated_at: true,
    },
    orderBy: {
      level: "asc",
    },
  });

  const admin_roles = rolesData || [];
  const roleIdToNameMap = new Map<string, string>();
  admin_roles.forEach((role) => roleIdToNameMap.set(role.id, role.name));

  // Fetch admin_role_permissions
  console.log("🔗 Fetching admin_role_permissions from database...");
  const rolePermissionsData = await prisma.admin_role_permissions.findMany({
    select: {
      role_id: true,
      permission_id: true,
    },
  });

  const admin_role_permissions: Record<string, string[]> = {};

  rolePermissionsData?.forEach((rp) => {
    const roleName = roleIdToNameMap.get(rp.role_id);
    const permissionName = permissionIdToNameMap.get(rp.permission_id);

    if (roleName && permissionName) {
      if (!admin_role_permissions[roleName]) {
        admin_role_permissions[roleName] = [];
      }
      admin_role_permissions[roleName].push(permissionName);
    }
  });

  const fileContent = `// This file is auto-generated by scripts/generate-permissions.ts
// Do not modify this file directly.

export const admin_permissions = ${JSON.stringify(admin_permissions, null, 2)} as const;

export const permissions = ${JSON.stringify(permissions, null, 2)} as const;

export const admin_roles = ${JSON.stringify(admin_roles, null, 2)} as const;

export const admin_role_permissions = ${JSON.stringify(admin_role_permissions, null, 2)} as const;

export type Permission = typeof admin_permissions[number]["name"];

`;

  const filePath = path.join(
    process.cwd(),
    "packages",
    "core",
    "common",
    "src",
    "auth",
    "permissions",
    "index.ts",
  );

  fs.writeFileSync(filePath, fileContent, "utf8");
  console.log(`✅ Permissions file generated at: ${filePath}`);
  console.log(`   - ${admin_permissions.length} permissions`);
  console.log(`   - ${admin_roles.length} roles`);
  console.log(
    `   - ${Object.keys(admin_role_permissions).length} role-permission mappings`,
  );
}

generatePermissionsFile()
  .catch((e) => {
    console.error("❌ Error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
