-- Add Counters and Status to Documents
ALTER TABLE modules.documents
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'PUBLIC',
ADD COLUMN IF NOT EXISTS comment_status VARCHAR(20) DEFAULT 'ALLOW',
ADD COLUMN IF NOT EXISTS blame_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS file_count INTEGER DEFAULT 0;

-- Add Counters to Comments
ALTER TABLE modules.comments
ADD COLUMN IF NOT EXISTS blame_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS file_count INTEGER DEFAULT 0;
